# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: JSONp
# Description of the Site
description: A portfolio of dabbles
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: https://user-images.githubusercontent.com/24516535/258889692-5ee9e4d8-0d56-4bda-aec1-64c3ba129c95.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://user-images.githubusercontent.com/24516535/258672300-4f9a9a0c-4d10-41ab-afb2-515455583f02.gif

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: jpell19@gmail.com
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: jason-pellegrino
github_username:  jpell19
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: JSONp
# URL for the Image of the Author
author-image: https://user-images.githubusercontent.com/24516535/265223353-760894ed-448d-4a23-8347-9eac88cdc673.gif

# 60 Words About the Author
author-about: "My guiding compass oscillates around three synergistic passions: gathering and analyzing data, building models to simulate or infer a likely future, and crafting an appropriate communication medium to tailor the transfer of knowledge to a target audience.  I want to improve our ability to communicate as a global society consisting of people with many different languages, cultures, and traditions by leveraging AI to create a much more accessible interface for users to generate multimodal, 3D, real-time, and interactive virtual experiences.  A much gentler learning curve for such a tool would allow just about anyone to truly express themselves and their intent (any emotion, real-life experience, theoretical mathematical object, or fantastical story) while reducing miscommunications such as language gaps, word ambiguity, and domain specific jargon."
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://jpell19.github.io

contact-image: https://user-images.githubusercontent.com/24516535/260200661-3688bc07-7169-4a77-81bb-6d4a88201d25.jpg

bootwatch: cyborg 

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
